services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    GeorgRinger\NewsImporticsxml\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    GeorgRinger\NewsImporticsxml\Command\ImportCommand:
        tags:
            -   name: 'console.command'
                command: 'news:importicsxml'

    GeorgRinger\NewsImporticsxml\Jobs\ImportJob:
        public: true

    GeorgRinger\NewsImporticsxml\EventListener\NewsImportListener:
        tags:
            -   name: event.listener
                identifier: 'newsimporticsxml-newsimportlistener'
                event: GeorgRinger\News\Event\NewsImportPostHydrateEvent
